ansible_python_interpreter: /usr/bin/python3
solr_host: "{{ ansible_host | default(inventory_hostname) }}"
users:
  - name: fat
    comment: "fat user"
    shell: /bin/bash
    groups: [sudo]
    ssh_pubkey_file: "fat_ed25519.pub"
