solr_version: "9.10.1"
solr_flavor: "slim"

# must match the artifact you download
# e.g. solr-9.10.1-slim.tgz.sha512 -> copy ONLY the hash, not filename
solr_sha512: "sha512:23915ba0c9eba81d9ed7dd46bf3dfa748a1cf12cfd1d2bc3c37e3022893b8d45a6d6dc078ee79e33c0367191c3e4f2d1df3c6f5705331ccfe13d6b1287812eb0 *solr-9.10.1.tgz"

solr_host: "0.0.0.0"
solr_port: 8983

solr_xms: "1g"
solr_xmx: "1g"
