- name: install samba package
  tags: samba
  become: true
  ansible.builtin.package: 
     name:
        - samba 
        - freeipa-client-samba
        - freeipa-client-epn
        - freeipa-common
        - freeipa-healthcheck
     state: present
