- name: install samba package
  tags: samba
  package: 
       name:
            - samba 
            - freeipa-client-samba
            - freeipa-client-epn
            - freeipa-common
            - freeipa-healthcheck
