---
- name: Create
  hosts: localhost
  gather_facts: false
  tasks:
    - name: Create and start container(s)
      community.docker.docker_container:
        name: "{{ item.name }}"
        image: "{{ item.image }}"
        state: started
        command: "{{ item.command | default('sleep 1d') }}"
        log_driver: json-file
      loop: "{{ molecule_yml.platforms }}"

