#- name: Add SSH key for fat
#  tags: always
#  ansible.builtin.authorized_key:
#    user: fat
#    key: "ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIDQOgHVbk8BNQAKgjQS5AMF3qtCZw+WgFcLNWQCNPCO7 ansible"

- name: Generate sshd_config from template
  tags: ssh
  ansible.builtin.template:
    src: "{{ ssh_template_file }}"
    dest: /etc/ssh/sshd_config
    owner: root
    group: root
    mode: "0644"
  notify: restart_sshd
